version: "3.5"

services:
  postgres:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
